name: Validate build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths-ignore:
      - .github/**

jobs:
  validate-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Configure environment
        run: |
          echo "BE_HOST=${{ secrets.BE_HOST }}" >> $GITHUB_ENV
          echo "BE_X_API_KEY=${{ secrets.BE_X_API_KEY }}" >> $GITHUB_ENV
      
      - name: Build project
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 30
          max_attempts: 5
          command: ./build.sh
