name: Validate build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths-ignore:
      - .github/**

jobs:
  validate-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Configure environment
        run: |
          echo "VITE_FIREBASE_API_KEY={{ env.VITE_FIREBASE_API_KEY }}" > .env
          sed -i "/baseToReplace/c\base: '/zalihe-krvi'," vite.config.js

      - name: Install dependencies
        run: |
          npm install
          cd scrapper && npm install && cd ..

      - name: Collect data
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 30
          max_attempts: 5
          command: cd scrapper && node index.js && cd ..

      - name: Build project
        run: npm run build
